import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { TOASTER_PROPS } from "@/lib/toast";



export const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-baseColor-100 text-[13px] sm:text-sm ${montserrat.className} antialiased`}
      >
         <Toaster {...TOASTER_PROPS} />
        {children}
      </body>
    </html>
  );
}
